version: '3.8'

services:


  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: store-keycloak
    restart: unless-stopped
    command: [ "start-dev" ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import:ro
    ports:
      - "8180:8080"
    networks:
      - store-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -v http://localhost:8080/q/health/live || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s




  mysql:
    image: mysql:8.0
    container_name: store-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: basic-auth-store
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - store-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  backend:
    image: eclipse-temurin:21-jdk
    container_name: store-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend/target:/app
    working_dir: /app
    command: java -jar backend-0.0.1-SNAPSHOT.jar
    environment:
      SPRING_PROFILES_ACTIVE: prod
      KEYCLOAK_ENDPOINT: http://store-keycloak:8080
      JWK_SET_URI: http://store-keycloak:8080/realms/store-security/protocol/openid-connect/certs
    depends_on:
      mysql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - store-network

  frontend:
    image: nginx:alpine
    container_name: store-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    volumes:
      - ./frontend/dist/frontend/browser:/usr/share/nginx/html:ro
    networks:
      - store-network

volumes:
  db-data:

networks:
  store-network:
    driver: bridge
